### ISSUE TITLE
group feature for 100 people not working 

### ISSUE THREAD

**Issue by kaushikprabhu123** [Neevethamanickam/Whatsup_messanger_Application#9]
Hi  @Neevethamanickam,

group feature for 100 people not working, could loading error and slowness.

kindly review and do the needfull or else please revert the feature and add my group features which i developed for 200 peolple.

i have testted by implementing in branch , my side its effective and could see improvements.

**Comment by Neevethamanickam** [comment]
Hi @kaushikprabhu123 ,

i have updated the feature for 200 members and group call, kindly review and suggest me if any further changes needed for this application.
